import { StyleSheet } from "react-native";
import { CssColors } from "./css_colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: CssColors.appBackground,
  },
  center_align: {
    flex: 1,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  container_document: {
    backgroundColor: CssColors.appBackground,
    width: "100%",
    height: "100%",
    marginBottom: 90,
  },
  marginTopTen: {
    marginTop: 10,
  },
  marginBottomTen: {
    marginBottom: 10,
  },
  document_container: {
    flex: 1,
    backgroundColor: CssColors.appBackground,
  },
  primary_input: {
    fontSize: 14,
    textAlign: "left",
    height: 56,
    borderBottomColor: CssColors.primaryBorder,
    borderBottomWidth: 1,
    alignSelf: "stretch",
    margin: 20,
    color: "black",
  },
  secondary_input: {
    color: "black",
    fontSize: 14,
    textAlign: "left",
    height: 56,
    borderBottomColor: CssColors.primaryBorder,
    borderBottomWidth: 1,
    alignSelf: "stretch",
    marginHorizontal: 20,
    marginVertical: 10,
  },
  select_list_document: {
    borderBottomColor: CssColors.primaryBorder,
    borderBottomWidth: 1,
    borderRadius: 0,
    elevation: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
    color: CssColors.primaryPlaceHolderColor,
    paddingLeft: 0,
    paddingRight: 0,
  },
  address_left_input: {
    color: "black",
    fontSize: 14,
    textAlign: "left",
    height: 56,
    borderBottomColor: CssColors.primaryBorder,
    borderBottomWidth: 1,
    alignSelf: "stretch",
    marginLeft: 20,
    marginRight: 10,
    width: "40%",
  },
  address_right_input: {
    color: "black",
    fontSize: 14,
    textAlign: "left",
    height: 56,
    borderBottomColor: CssColors.primaryBorder,
    borderBottomWidth: 1,
    alignSelf: "stretch",
    marginLeft: 10,
    marginRight: 20,
    width: "42%",
  },
  state_dropdown_container: {
    color: "black",
    fontSize: 14,
    textAlign: "left",
    alignSelf: "stretch",
    marginLeft: 10,
    marginRight: 20,
    marginTop: 10,
    width: "42%",
  },
  primary_textarea: {
    fontSize: 14,
    textAlign: "left",
    maxHeight: 100,
    borderWidth: 1,
    borderColor: CssColors.primaryBorder,
    margin: 20,
    padding: 10,
    minHeight: 100,
  },
  primary_title: {
    fontSize: 16,
    textAlign: "center",
    color: CssColors.primaryColor,
    fontWeight: "bold",
  },
  primary_button: {
    backgroundColor: CssColors.primaryColor,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    margin: 20,
    borderRadius: 20,
  },
  primary_button_disabled: {
    backgroundColor: CssColors.primaryButtonDisabledBgColor,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    margin: 20,
    borderRadius: 20,
  },
  primary_button_text: {
    color: CssColors.white,
    fontSize: 16,
    height: 52,
    paddingTop: 15,
    alignSelf: "center",
  },
  primary_button_text_disabled: {
    color: CssColors.primaryPlaceHolderColor,
    fontSize: 16,
    height: 52,
    paddingTop: 15,
    alignSelf: "center",
  },
  paddinglr_45: {
    paddingLeft: 45,
    paddingRight: 45,
  },
  login_logo: {
    width: 87,
    height: 87,
    marginBottom: 20,
  },
  secondary_button_text: {
    color: CssColors.primaryColor,
    fontSize: 16,
    paddingLeft: 10,
  },
  secondary_button_text_disabled: {
    opacity: 0.5,
    fontSize: 16,
    paddingLeft: 10,
  },
  error_icon: {
    height: 27,
    width: 27,
  },
  login_error_container: {
    flexDirection: "row",
    alignSelf: "flex-start",
    paddingLeft: 20,
    paddingRight: 20,
  },
  document_error_container: {
    flexDirection: "row",
    alignSelf: "center",
    paddingLeft: 20,
    paddingRight: 20,
    marginTop: 10,
  },
  login_error_text: {
    fontSize: 16,
    color: CssColors.errorTextColor,
    paddingLeft: 10,
    paddingTop: 2.2,
  },
  document_error_text: {
    fontSize: 14,
    color: CssColors.errorTextColor,
    paddingLeft: 10,
    paddingTop: 2.2,
  },
  profile_sub_title: {
    color: CssColors.textColorSecondary,
    fontSize: 12,
    textAlign: "center",
  },
  gender_text: {
    alignSelf: "flex-start",
    paddingLeft: 20,
    paddingBottom: 10,
    marginTop: 20,
    color: CssColors.primaryPlaceHolderColor,
  },
  gender_inputs: {
    alignSelf: "flex-start",
    flexDirection: "row",
    paddingLeft: 20,
    paddingRight: 20,
    color: "black",
  },
  close_icon_container: {
    flex: 1,
    alignSelf: "flex-end",
    paddingTop: 25,
    marginBottom: 35,
  },
  close_icon: {
    width: 25,
    height: 25,
  },
  upload_icon: {
    width: 25,
    height: 25,
    alignSelf: "center",
  },
  gender_buttons: {
    paddingLeft: 34,
    paddingRight: 34,
    paddingTop: 10,
    paddingBottom: 10,
    borderColor: CssColors.primaryBorder,
    marginRight: 10,
    borderWidth: 1,
    backgroundColor: CssColors.white,
  },
  gender_button_active: {
    paddingLeft: 34,
    paddingRight: 34,
    paddingTop: 10,
    paddingBottom: 10,
    borderColor: CssColors.primaryBorder,
    marginRight: 10,
    borderWidth: 1,
    backgroundColor: CssColors.primaryColor,
  },
  gender_button_text: {
    color: CssColors.primaryColor,
  },
  gender_button_text_active: {
    color: CssColors.white,
  },
  primary_dropdown: {
    backgroundColor: "transparent",
    marginLeft: 20,
    marginRight: 20,
    fontSize: 14,
    color: CssColors.primaryPlaceHolderColor,
  },
  upload_documents_container: {
    flexDirection: "row",
    marginLeft: 20,
    marginLeft: 20,
    justifyContent: "center",
  },
  upload_document: {
    padding: 20,
    borderColor: CssColors.primaryBorder,
    borderWidth: 1,
    marginRight: 20,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  scan_document_title: {
    marginTop: 16,
    fontSize: 20,
    color: CssColors.primaryTitleColor,
    lineHeight: 28,
  },
  scan_document_sub_title: {
    marginTop: 12,
    fontSize: 14,
    lineHeight: 24,
    color: CssColors.primaryPlaceHolderColor,
  },
  scan_document_desc: {
    marginTop: 12,
    fontSize: 12,
    lineHeight: 20,
    color: CssColors.primaryBorder,
  },
  scan_note_container: {
    flexDirection: "row",
    marginTop: 12,
    backgroundColor: CssColors.errorBackgroundColor,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
  },
  error_scan_text: {
    fontSize: 12,
    lineHeight: 20,
    color: CssColors.primaryPlaceHolderColor,
    paddingLeft: 15,
  },
  button_outline: {
    borderColor: CssColors.primaryBorder,
    borderWidth: 1,
    flexGrow: 1,
  },
  button_outline_text: {
    fontSize: 14,
    lineHeight: 18,
    paddingTop: 10,
    paddingBottom: 10,
    color: CssColors.primaryColor,
    textAlign: "center",
  },
  margin_right_10: {
    marginRight: 10,
  },
  icon_button_container: {
    flexDirection: "row",
    flex: 1,
    justifyContent: "space-between",
    paddingLeft: 12,
    paddingRight: 12,
    marginTop: 20,
    marginBottom: 20,
  },
  scan_icon: {
    width: 112,
    height: 120,
  },
  back_icon_container: {
    position: "absolute",
    top: 40,
    left: 20,
  },
  flex_row: {
    flexDirection: "row",
  },
  home_details_container: {
    borderRadius: 12,
    marginHorizontal: 10,
    marginTop: 12,
    marginBottom: 10,
    backgroundColor: CssColors.white,
  },
  shadowPropQuickAction: {
    shadowColor: CssColors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 1,
    elevation: 5,
  },
  shadowProp: {
    shadowColor: CssColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  home_details_title: {
    color: CssColors.primaryPlaceHolderColor,
    marginVertical: 10,
    marginHorizontal: 10,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "800",
  },
  home_details_btn_container: {
    flex: 1,
    alignItems: "center",
    marginLeft: 10,
    paddingVertical: 15,
    borderRadius: 4,
  },
  home_details_inner_container: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginRight: 10,
  },
  home_details_icon_image: {
    width: 46,
    height: 46,
  },
  home_details_inner_text: {
    color: CssColors.primaryPlaceHolderColor,
    fontSize: 12,
    lineHeight: 12,
    marginTop: 8,
    fontWeight: "600",
  },
  home_quick_links_container: {
    borderColor: CssColors.homeDetailsBorder,
    borderWidth: 0.5,
    flexGrow: 0,
    backgroundColor: CssColors.white,
    marginHorizontal: 12,
    marginTop: 10,
    borderRadius: 6,
    shadowColor: CssColors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  general_container: {
    flex: 1,
    flexGrow: 1,
    backgroundColor: CssColors.appBackground,
  },
  image_100_width: {
    resizeMode: "contain",
    flex: 1,
    aspectRatio: 1, // Your aspect ratio
  },
  imgContainer: {
    flexDirection: "row",
  },
  itemWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomColor: CssColors.homeDetailsBorder,
    borderTopColor: "transparent",
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderWidth: 1,
  },
  leftWrapper: {
    flexDirection: "row",
    alignItems: "center",
  },
  image: {
    height: 24,
    width: 24,
  },
  titlesWrapper: {
    marginLeft: 12,
  },
  title: {
    fontSize: 14,
    color: CssColors.primaryColor,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 14,
    color: CssColors.lightGrey,
  },
  rightWrapper: {
    alignItems: "flex-end",
  },
  listI_itemWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomColor: CssColors.homeDetailsBorder,
    borderTopColor: "transparent",
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderWidth: 1,
  },
  listI_leftWrapper: {
    flexDirection: "row",
    alignItems: "center",
  },
  listI_icon_left: {
    alignSelf: "flex-start",
  },
  listI_titlesWrapper: {
    marginLeft: 12,
    maxWidth: "90%",
  },
  listI_title: {
    fontSize: 14,
    color: CssColors.primaryColor,
  },
  listI_subtitle: {
    marginTop: 4,
    fontSize: 14,
    color: CssColors.lightGrey,
  },
  listI_rightWrapper: {
    alignItems: "flex-end",
  },
  money_grow: {
    position: "absolute",
    left: 55,
    top: 20,
  },
  new_chits_container: {
    backgroundColor: CssColors.new_chits_background,
    flex: 1,
  },
  newChits_tags: {
    backgroundColor: CssColors.white,
    height: 42,
    paddingVertical: 7,
    paddingLeft: 10,
    flexDirection: "row",
  },
  newChits_tags_text: {
    color: CssColors.primaryPlaceHolderColor,
    fontSize: 12,
    lineHeight: 17,
  },
  newChits_tags_text_active: {
    color: CssColors.white,
    fontSize: 12,
    lineHeight: 17,
  },
  newChits_tags_container: {
    borderColor: CssColors.primaryBorder,
    borderWidth: 1,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: CssColors.primaryBorder,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginRight: 10,
  },
  newChits_tags_container_active: {
    borderColor: CssColors.primaryBorder,
    borderWidth: 1,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: CssColors.primaryBorder,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginRight: 10,
    backgroundColor: CssColors.primaryTitleColor,
  },
  chit_container: {
    marginBottom: 15,
    marginHorizontal: 12,
    paddingLeft: 10,
    paddingTop: 10,
    borderRadius: 12,
    backgroundColor: CssColors.white,
  },
  mychit_acc_copy_container: {
    marginBottom: 15,
    marginHorizontal: 12,
    paddingVertical: 15,
    borderRadius: 12,
    paddingLeft: 10,
    backgroundColor: CssColors.white,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  chits_avatar: {
    borderRadius: 50,
  },
  chit_container_row1: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  chit_container_row1_left: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  new_chits_amount_text: {
    color: CssColors.textColorSecondary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    width: '90%'
  },
  new_chits_amount_text_myChitDetails: {
    color: CssColors.textColorSecondary,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "600",
    width: '60%'
  },
  new_chits_amount_inner_text: {
    color: CssColors.textColorSecondary,
    fontSize: 8,
    lineHeight: 16,
    paddingLeft: 5,
  },
  new_chits_sub_tags: {
    color: CssColors.primaryPlaceHolderColor,
    fontSize: 8,
    backgroundColor: CssColors.newChitTagBackground,
    padding: 2,
    borderRadius: 4,
    marginRight: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  new_chits_tickets_left: {
    color: CssColors.errorTextColor,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 7,
  },
  chit_container_row2: {
    flexDirection: "row",
    paddingVertical: 10,
    justifyContent: "space-between"
  },
  chit_container_row2_inner_container_last: {
    paddingRight: 10,
  },
  chit_container_row2_inner_header: {
    color: CssColors.lightGreyTwo,
    fontSize: 8,
    fontWeight: '400'
  },
  chit_container_row2_inner_header_info: {
    color: CssColors.primaryPlaceHolderColor,
    fontSize: 12,
    fontWeight: "400",
    paddingTop: 5,
  },
  vertical_line: {
    borderRightColor: CssColors.homeDetailsBorder,
    borderTopColor: "transparent",
    borderLeftColor: "transparent",
    borderBottomColor: "transparent",
    borderWidth: 1,
  },
  chit_container_subscriber_count: {
    backgroundColor: CssColors.appBackground,
    paddingLeft: 20,
    paddingBottom: 4,
    color: CssColors.primaryColor,
    fontSize: 8,
    lineHeight: 16,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  chit_container_row3: {
    flexDirection: "row",
    paddingBottom: 10,
    paddingRight: 10,
    justifyContent: "space-between",
  },
  chit_container_row3_mychit: {
    flexDirection: "row",
    paddingBottom: 10,
    paddingRight: 10,
    justifyContent: "space-between",
    alignItems: "center",
  },
  chit_container_row3_sucbribe: {
    flexDirection: "row",
    paddingBottom: 10,
    paddingRight: 10,
    justifyContent: "flex-end",
  },
  chit_container_row3_vacant: {
    flexDirection: "row",
    width: 150,
  },
  new_chits_primary_button_container: {
    backgroundColor: CssColors.textColorSecondary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  new_chits_primary_button_container_two: {
    backgroundColor: CssColors.primaryColor,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  payDueButton: {
    backgroundColor: CssColors.white,
    borderWidth: 1,
    borderColor: CssColors.textColorSecondary,
    color: CssColors.textColorSecondary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  payDueButtonText: {
    color: CssColors.textColorSecondary,
    fontSize: 12,
    fontWeight: "600"
  },
  new_chits_primary_button_text: {
    color: CssColors.white,
    fontSize: 12,
    fontWeight: "600",
  },
  pdf_icon: {
    paddingRight: 10,
  },
  pdf_certificate_button_text: {
    color: CssColors.primaryColor,
    fontSize: 12,
    lineHeight: 18,
    textDecorationColor: CssColors.primaryColor,
    textDecorationStyle: "solid",
    textDecorationLine: "underline",
  },
  pdf_certificate_button_container: {
    flexDirection: "row",
    alignItems: 'center'
  },
  pledged_chit_logo_icon: {
    height: 120,
    width: 120,
    marginVertical: 16
  },
  bottomsheet_title1_secondary: {
    color: CssColors.textColorSecondary,
    fontSize: 16,
    fontWeight: "600",
  },
  pledged_chit_container: {
    alignItems: 'center',
    width: '100%',
  },
  pledged_chit_icon_container: {
    height: 120,
    width: 120,
    borderRadius: 60,
    backgroundColor: CssColors.iconBackground,
    marginVertical: 16,
    alignItems: 'center',
    justifyContent: 'center'
  },
  new_chits_tag_container: {
    width: 54,
    height: 18,
  },
  new_chits_logo_icon: {
    width: 30,
    height: 30,
    marginRight: 10,
    marginTop: 5
  },
  home_avatar_icon: {
    width: 30,
    height: 30,
  },
  my_completed_chit_icon: {
    width: 25,
    height: 25,
  },
  margin_right_15: { marginRight: 15 },
  margin_right_25: { marginRight: 25 },
  margin_left_15: { marginLeft: 15 },
  margin_left_12: { marginLeft: 12 },
  margin_left_10: { marginLeft: 10 },
  margin_bottom_20: { marginBottom: 20 },
  margin_bottom_5: { marginBottom: 5 },
  new_chits_details_logo_icon: {
    width: 52,
    height: 52,
    marginRight: 10,
  },
  new_chits_pdf_icon: {
    marginRight: 5,
  },
  new_chits_details_certificate_icon: {
    width: 25,
    height: 25,
    marginRight: 10,
    color: CssColors.primaryColor,
  },
  new_chits_details_certificate_pdf_icon: {
    width: 25,
    height: 25,
    marginLeft: "auto",
    marginRight: "auto",
  },
  new_chits_tag_text: {
    alignSelf: "center",
    overflow: "hidden",
    fontSize: 10,
    lineHeight: 16,
    paddingLeft: 2,
    color: CssColors.green,
  },
  fixed_footer_one_container: {
    height: 70,
    backgroundColor: CssColors.white,
    borderTopColor: "#e6e6e6",
    borderTopWidth: 1,
    padding: 10,
    flexDirection: "row",
    marginBottom: 0,
    alignItems: "center",
  },
  fixed_footer_one_container_inner: {
    width: "50%",
  },
  text_type_5: {
    color: CssColors.lightGreyThree,
    fontSize: 10,
  },
  button_two: {
    backgroundColor: CssColors.textColorSecondary,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 20,
  },
  button_two_disabled: {
    backgroundColor: CssColors.primaryButtonDisabledBgColor,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 20,
  },
  button_two_text: {
    fontSize: 14,
    color: CssColors.white,
    fontWeight: '600'
  },
  button_two_text_disabled: {
    fontSize: 14,
  },
  button_three: {
    backgroundColor: CssColors.primaryColor,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 20,
  },
  button_three_disabled: {
    backgroundColor: CssColors.primaryButtonDisabledBgColor,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 20,
  },
  button_three_text: {
    fontSize: 14,
    color: CssColors.white,
  },
  button_three_text_disabled: {
    fontSize: 14,
    color: CssColors.primaryPlaceHolderColor,
  },
  fontsize16: {
    fontSize: 16,
    color: CssColors.primaryPlaceHolderColor,
  },
  fontsize14: {
    fontSize: 14,
    color: CssColors.primaryPlaceHolderColor,
  },
  fontsize12: {
    fontSize: 12,
    color: CssColors.primaryBorder,
  },
  new_chit_fixed_footer_input_container: {
    width: "80%",
    borderBottomColor: CssColors.primaryBorder,
    borderTopColor: "transparent",
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderWidth: 1,
    flexDirection: "row",
    paddingBottom: 3,
  },
  new_chit_fixed_footer_input_prefix: {
    paddingRight: 2,
    fontSize: 18,
    color: CssColors.primaryColor,
    paddingTop: 1,
  },
  new_chit_fixed_footer_input: {
    fontSize: 18,
    color: CssColors.primaryColor,
    width: "100%",
    padding: 0,
  },
  vacant_chit_text1: {
    color: CssColors.primaryBorder,
    fontSize: 8,
  },
  vacant_chit_text2: {
    color: CssColors.primaryColor,
    fontSize: 8,
    lineHeight: 19,
  },
  bottomsheet_title1: {
    color: CssColors.primaryPlaceHolderColor,
    fontSize: 16,
    fontWeight: "600",
  },
  bottomsheet_title2: {
    color: CssColors.primaryPlaceHolderColor,
    fontSize: 12,
  },
  bottomsheet_text1: {
    color: CssColors.primaryPlaceHolderColor,
    fontSize: 8,
  },
  read_more: {
    fontSize: 8,
    textDecorationColor: "black",
    textDecorationStyle: "solid",
    textDecorationLine: "underline",
    position: "relative",
    top: 2.5,
    paddingLeft: 5,
    color: CssColors.primaryPlaceHolderColor
  },
  bottomsheet_text2: {
    color: CssColors.primaryBorder,
    fontSize: 10,
  },
  bottomsheet_text3: {
    color: CssColors.primaryBorder,
    fontSize: 12,
  },
  bottomsheet_checkbox1: {
    flexDirection: "row",
    alignItems: "center",
    alignContent: "center",
    marginVertical: 10,
  },
  padding_bottom_4: {
    paddingBottom: 4,
  },
  padding_left_4: {
    paddingLeft: 4,
  },
  margin_left_4: {
    marginLeft: 4,
  },
  padding_bottom_16: {
    paddingBottom: 16,
  },
  padding_top_10: { paddingTop: 10 },
  padding_left_10: { paddingLeft: 10 },
  min_amount_error_container: {
    backgroundColor: CssColors.red,
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  min_amount_error_text: {
    color: CssColors.white,
    fontSize: 14,
  },
  customThumb: {
    width: 18,
    height: 18,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 30,
    borderColor: CssColors.locationPin,
    backgroundColor: CssColors.white,
    borderWidth: 1,
    top: -12,
    transform: [{ rotate: "45deg" }],
    justifyContent: 'center',
    alignItems: 'center',
  },
  customThumbTextContainer: {
    transform: [{ rotate: "-45deg" }],
    justifyContent: 'center',
    alignItems: 'center',
  },
  customThumbText: {
    color: CssColors.locationPin,
    textAlign: "center",
    fontSize: 8,
    fontWeight: '600',
  },
  sliderContainer: {
    width: 60,
    height: 25,
    marginHorizontal: 4,
    justifyContent: 'center',
  },
  vacant_chit_text2: {
    color: CssColors.primaryColor,
    fontSize: 9,
    textAlign: 'center',
    fontWeight: '500',
    minWidth: 18,
  },
  chit_container_row3_vacant: {
    flexDirection: "row",
    alignItems: 'center',
    width: 150,
  },
  sliderContainer_mychit: {
    width: 50,
    height: 5,
    top: -10,
    paddingLeft: 2,
    paddingRight: 2,
  },
  mychitStatusText: {
    fontSize: 8,
    color: CssColors.primaryBorder,
  },
  mychitStatusTextTwo: {
    fontSize: 8,
    color: CssColors.primaryPlaceHolderColor,
  },
  myChitEnrollmentText: {
    fontSize: 8,
    color: CssColors.errorTextColor,
  },
  title_type_1: {
    fontSize: 14,
    lineHeight: 24,
    color: CssColors.primaryPlaceHolderColor,
    fontWeight: "bold",
  },
  Login_input_container: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: 'gray',
    borderRadius: 20,
    margin: 15,
    paddingHorizontal: 10,
  },
  Login_input: {
    flex: 1,
    fontSize: 16,
    padding: 10,
    color: CssColors.primaryPlaceHolderColor
  },
  Login_input_iconContainer: {
    padding: 10,
  },
  borderBottom: {
    borderBottomColor: CssColors.homeDetailsBorder,
    borderBottomWidth: 1,
  }
});
