export const SiteTexts = {
    login_1_title: 'Please wait we will auto verify the OTP Sent to +91 ',
    login_1_subTitle: 'Your code will expire in 0:59sec',
    login_1_enter_otp: 'Enter OTP',
    login_1_button_title: 'Continue',
    login_1_resend_code: 'Resend code',
    profile_title: 'Thank you for joining with us!',
    profile_welcome: 'Welcome,',
    profile_subTitle: 'Please let us know you more.',
    profile_name: "Name*",
    profile_email: "E-mail (optional)",
    profile_button_title: "Continue",
    profile_button_text: "Submit",
    text_phone_number: "Phone Number*",
    login_2_title: "Let's Sign In or Create account with your phone number!",
    expiry_time_message: "Your code will expire in",
    text_sec: "sec",
    text_gender: "Gender*",
    text_document_type: "Choose Document Type",
    text_address_line: "Address line*",
    text_address_city: "City*",
    text_address_state: "State*",
    text_address_pin_code: "Pin code*",
    text_address_country: "Country*",
    text_aadhar_number: "Aadhar Number*",
    text_aadhar: "Aadhar",
    text_number: "Number",
    text_dob: "Date of Birth*",
    text_scan_document: "Scan Document",
    document_subtitle: "Document is mandatory to set-up your chit account",
    document_upload_desc: "Make sure your document is completely visible and all the details are visible",
    document_upload_info_message: "You may be asked for access to your camera or gallery to continue",
    text_gallery: "Gallery",
    text_camera: "Camera",
    text_logout: "Logout",
    text_dashboard: "Dashboard",
    error_phone_invalid: "Please enter valid phone number.",
    error_too_many_request: "Too Many Requests kindly come back after some time.",
    error_invalid_otp: "Invalid OTP code. Please enter again",
    error_otp_expired: "Your OTP code has expired!",
    error_user_disabled: "Your account is temprarily blocked, kindly come back after 24 hours",
    error_aadhar_invalid: "Aadhar can/should contain atleast/max 12 numbers only",
    error_pan_invalid: "PAN can/should contain atleast/max 10 alphabets or numbers only",
    error_dl_invalid: "Driving Licence can/should contain atleast/max 10 alphabets or numbers only",
    error_passport_invalid: "Passport can/should contain atleast/max 10 alphabets or numbers only",
    error_voter_id_invalid: "Voter ID can/should contain atleast/max 10 alphabets or numbers only",
    error_ration_invalid: "Ration ID can/should contain atleast/max 10 alphabets or numbers only",
    error_library_permissions: "You've refused to allow this appp to access your photos!",
    error_camera_permissions: "You've refused to allow this appp to access your camera!",
    chit_agreement_form_group_reg_branch: 'Group registered branch',
    chit_agreement_form_group_agr_para: 'Agreement parameters',
    chit_agreement_form_group_pso_num: 'PSO number',
    chit_agreement_form_group_pso_date: 'PSO Date',
    chit_agreement_form_group_grp_code: 'Group code',
    chit_agreement_form_group_chit_reg: 'Chit registrar',
    chit_agreement_form_group_chit_reg_addr: 'Chit registrar address',
    chit_agreement_form_group_foreman_addr: 'Foreman address',
    chit_agreement_form_group_no_of_tick: 'Number of tickets',
    chit_agreement_form_group_no_of_inst: 'No of intsallments',
    chit_agreement_form_group_first_inst_amo: 'First installment amount',
    chit_agreement_form_group_tkt_no: 'Ticket no',
    chit_agreement_form_group_chit_val: 'Chit value',
    chit_agreement_form_group_auc_time: 'Auction time',
    chit_agreement_form_group_auc_date: 'Auction date',
    chit_agreement_form_group_place_pf_auc: 'Place pf auction',
    chit_agreement_form_group_due_date: 'Due date',
    chit_agreement_form_group_dt_of_commence: 'Date of commencment',
    chit_agreement_form_group_dt_of_termi: 'Date of termination',
    chit_agreement_form_group_fd_amt: 'FD amount',
    chit_agreement_form_group_chit_dur: 'Total month(chit duration)',
    chit_agreement_form_group_dep_bank: 'Deposit bank and branch',
    chit_agreement_form_group_fd_rec_no: 'FD receipt no',
    chit_agreement_form_group_fd_date: 'FD date',
    chit_agreement_form_group_sub_sign: 'Subscriber signature',
    chit_agreement_form_group_foreman_sign: 'Foreman signature',
    chit_agreement_form_group_sel_sub: 'Select the subscriber*',
    chit_agreement_form_group_name_of_sub: 'Name of Subscriber*',
    chit_agreement_form_group_mob_no: 'Mobile number*',
    chit_agreement_form_group_sel_sub: 'Select the subscriber*',
    chit_agreement_form_group_nominee_name: 'Nominee name',
    chit_agreement_form_group_nominee_dob: 'Nominee date of birth',
    chit_agreement_form_group_nominee_rel: 'Nominee relationship',
    chit_agreement_form_group_terms_checkbox: 'I agree to the Terms and Conditions.',
    chit_enrollment_pop_up_title: 'Complete Chit Enrolment',
    chit_enrollment_pop_up_text_one: 'Enrolment is pending.',
    chit_enrollment_pop_up_text_two: 'Please complete following few steps.',
    chit_agreement_pop_up_title: 'Complete Chit Agreement',
    chit_agreement_pop_up_text_one: 'Agreement is pending.',
    chit_agreement_pop_up_text_two: 'Please complete following few steps.',
    continue_text: "Continue",
    text_subscribe_now: "Subscribe now",
    text_proceed_to_pay: "Proceed to pay",
    document_max_filesize_limit: "Your file should be less than 5 MB",
    done_text:'Done'
}